go-mod: [ "go.mod", "go.sum" ]
common-libs: [ "pkg/**", "internal/**" ]
history-exporter: [ "cmd/history-exporter/**/*!(_test).go" ]
history-exporter-tests: [ "cmd/history-exporter/**/*_test.go" ]
gh-action: [ "cmd/gh-action/**/*!(_test).go" ]
gh-action-tests: [ "cmd/gh-action/**/*_test.go" ]
