name: Push Entry Point

on:
  push:
    branches:
      - test-push-workflow

jobs:
  show-github-event:
    runs-on: [ self-hosted, small ]
    steps:
      - name: print whole context
        env:
          GITHUB_CONTEXT:  ${{ toJson(github) }}
          VARS_CONTEXT:  ${{ toJson(vars) }}
        run: |
          echo "GITHUB_CONTEXT is $GITHUB_CONTEXT"
          echo "VARS_CONTEXT is $VARS_CONTEXT"

  build-go-projects:
    strategy:
      matrix:
        go-component: [ 'gh-action', 'history-exporter' ]
    uses: ./.github/workflows/50_go_build-one-component.yml
    secrets: inherit
    name: 'Golang: ${{ matrix.go-component }}'
    with:
      component-name: ${{ matrix.go-component }}
      base-sha: ${{ github.event.push.after }}
      pack-to-docker-image: true
      go-build-cache-restore-or-update: 'update'
      go-mod-cache-restore-or-update: 'update'

  final-step:
    needs: [ build-go-projects ]
    if: ${{ always() }}
    runs-on: [ self-hosted, small ]
    steps:
      - name: Print final message
        run: |
          echo Thats it.
