name: Worfklows Sanity Checks

on:
  workflow_call:

jobs:
  do-sanity-checks:
    runs-on: [ self-hosted, small ]
    name: GitHub Actions Sanity Checks
    steps:
      - uses: actions/checkout@6ccd57f4c5d15bdc2fef309bd9fb6cc9db2ef1c6 # v4.1.7
        with:
          sparse-checkout: |
            .github/
          sparse-checkout-cone-mode: false
      - uses: reviewdog/action-actionlint@053c5cf55eed0ced1367cdc5e658df41db3a0cce # v1.59.0
        with:
          fail_level: error
      - name: Verify Go-components lists
        run: |
          # wat? why do we need `jq` after `yq`?
          # it happens that yq adds extra new line to the output
          # but not in every cases, but sometimes. No explanation.
          yq 'del(.trigger_all) | keys | sort | to_json' \
            .github/file-filters/go-components.yaml \
            | jq . \
            > from-file-filters.json
          yq '.env.list-of-all-components | from_json | sort | to_json' \
            .github/workflows/00_pull-request-entry-point.yml \
            | jq . \
            > from-00_pull-request-entry-point.json
          yq '.jobs.build-go-projects.strategy.matrix.go-component | sort | to_json' \
            .github/workflows/00_push-entry-point.yml \
            jq . \
            > from-00_push-entry-point.json

            exit_code=0
            if diff -q from-file-filter.json from-00_pull-request-entry-point.json; then
              echo "Components lists differs in file-filters and 00_pull-request-entry-point workflow"
              exit_code=$(( exit_code + 1 ))
            fi
            if diff -q from-file-filter.json from-00_push-entry-point.json; then
              echo "Components lists differs in file-filters and 00_push-entry-point workflow"
              exit_code=$(( exit_code + 2 ))
            fi

            exit ${exit_code}
