name: "Golang: Build one component"

on:
  workflow_call:
    inputs:
      component-name:
        required: true
        type: string
      go-mod-path:
        required: false
        type: string
        default: 'go.mod'
      arch-os-preset:
        required: false
        type: string
        default: 'wip_ignore_for_now'
      pack-to-docker-image:
        required: false
        type: boolean
        default: false
      base-sha:
        required: false
        type: string
        default: 'anysha'

jobs:
  build-go-component:
    strategy:
      matrix:
        goarch: [ 'amd64', 'arm64', '386', 'arm' ]
        goos: [ 'linux', 'windows', 'darwin' ]
        exclude:
          - goarch: '386'
            goos: 'darwin'
          - goarch: 'arm'
            goos: 'darwin'
    uses: ./.github/workflows/50_go_build-one-arch-one-os-one-path.yml
    secrets: inherit
    name: '${{ inputs.component-name }} ${{ matrix.goos }}/${{ matrix.goarch }}'
    with:
      cmd-path: './cmd/${{ inputs.component-name }}'
      goarch: ${{ matrix.goarch }}
      goos: ${{ matrix.goos }}
      pack-to-docker-image: ${{ inputs.pack-to-docker-image }}
      base-sha: ${{ inputs.base-sha }}
