name: Sleep

on:
  pull_request:

jobs:
  just-sleep:
    runs-on: [self-hosted, small]
    container:
      image: 369495373322.dkr.ecr.eu-central-1.amazonaws.com/cloud:pinned
    steps:
    - name: Sleep and do something else
      run: |
        sleep 600
        curl -v https://neon.tech
