name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: neondatabase/gh-workflow-stats-action
          tags: |
            # branch event
            type=ref,enable=true,priority=600,prefix=,suffix=,event=branch
            # pull request event
            type=ref,enable=true,priority=600,prefix=pr-,suffix=,event=pr
            # tags event
            type=semver,pattern={{raw}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: false
        with:
          username: ${{ secrets.NEON_DOCKERHUB_USERNAME }}
          password: ${{ secrets.NEON_DOCKERHUB_PASSWORD }}

      - name: Build and publish
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
