name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  debug_s3_bucket:
    runs-on: [self-hosted, small]
    steps:
      - uses: hostwithquantum/setup-mc@main
        with:
          alias-name: hetzner-bucket
          alias-url: https://${{ vars.HETZNER_CACHE_REGION }}.${{ vars.HETZNER_CACHE_ENDPOINT }}
          alias-access-key: ${{ secrets.HETZNER_CACHE_ACCESS_KEY }}
          alias-secret-key: ${{ secrets.HETZNER_CACHE_SECRET_KEY }}
      - name: List bucket
        run: mc ls hetzner-bucket/${{ vars.HETZNER_CACHE_BUCKET }}
